name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Python noucell
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Étape 3 : Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Nettoyage des fichiers résiduels
      - name: Clean residual files
        run: |
          find . -name "__pycache__" -exec rm -r {} +
          find . -name "*.pyc" -exec rm -r {} +

      # Étape 5 : Configuration des variables d'environnement
      - name: Set environment variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=myselftest.settings" >> $GITHUB_ENV

      # Étape 6 : Exécution des tests avec couverture
      - name: Run tests with coverage
        env:
          DJANGO_SETTINGS_MODULE: myselftest.settings
        run: |
          pytest --ds=myselftest.settings --cov=myapp --cov-report=xml

      # Étape 7 : Téléversement du rapport de couverture sur Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true # Pour garantir que les erreurs de Codecov échouent la CI
