name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Run tests and generate coverage report
    - name: Run tests with coverage
      run: |
        pytest --cov=your_project --cov-report=xml

    # 5. List files (Debugging step)
    - name: List files for debugging
      run: ls -la

    # 6. Upload coverage to Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2  # Version stable v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Assurez-vous que le token est bien configuré
