name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout du code
    - name: Checkout code
      uses: actions/checkout@v3

    # Configuration de Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Installation des dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installe les dépendances

    # Exécution des tests avec couverture
    - name: Run tests with coverage
      run: |
        pytest --cov=myapp --cov-report=xml  # Exécute les tests et génère coverage.xml

    # Téléversement du rapport de couverture sur Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: coverage.xml  # Spécifie le fichier de couverture
        token: ${{ secrets.CODECOV_TOKEN }}  # Vous devez définir le token dans les secrets GitHub
